name: Release

on:
  push:
    branches: master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npx ci
    - name: Build
      run: npm run build
    - name: Lint
      run: npm run lint
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
